const fs = require('fs');
const path = require('path');

const iconName = process.argv[2];
if (!iconName) {
  console.error('Please provide an icon name.');
  process.exit(1);
}

const componentName = iconName.charAt(0).toUpperCase() + iconName.slice(1) + 'Icon';
const componentPath = path.join(__dirname, `../src/icons/${componentName}.tsx`);
const indexPath = path.join(__dirname, '../src/index.tsx');

const template = `/*
* NOTE: This file is autogenerated using the generate-icon.js script.
* Any changes made to this file will be overwritten when the script is run again.
*/
"use client";
import React from 'react';
import { AnimatedIconProps } from '../types';
import IconWrapper from './IconWrapper';

const ${componentName}: React.FC<AnimatedIconProps> = (props) => (
  <IconWrapper {...props}>
    {/* TODO: Add SVG path data here */}
  </IconWrapper>
);

export default ${componentName};
`;

fs.writeFileSync(componentPath, template);

const exportStatement = `export { default as ${componentName} } from './icons/${componentName}';\n`;
fs.appendFileSync(indexPath, exportStatement);

console.log(`Successfully created ${componentName} at ${componentPath}`);
console.log(`And exported it from ${indexPath}`);